/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_ACK_PB_H_INCLUDED
#define PB_ACK_PB_H_INCLUDED
#include "../nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AckProto {
    pb_callback_t seq;
} AckProto;

typedef struct _SAckProto {
    pb_callback_t droneId;
    uint64_t seq;
    /* return code, 0: success, 1: received, < 0: error */
    int32_t code;
} SAckProto;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AckProto_init_default                    {{{NULL}, NULL}}
#define SAckProto_init_default                   {{{NULL}, NULL}, 0, 0}
#define AckProto_init_zero                       {{{NULL}, NULL}}
#define SAckProto_init_zero                      {{{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AckProto_seq_tag                         1
#define SAckProto_droneId_tag                    1
#define SAckProto_seq_tag                        2
#define SAckProto_code_tag                       3

/* Struct field encoding specification for nanopb */
#define AckProto_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT64,   seq,               1)
#define AckProto_CALLBACK pb_default_field_callback
#define AckProto_DEFAULT NULL

#define SAckProto_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   droneId,           1) \
X(a, STATIC,   SINGULAR, UINT64,   seq,               2) \
X(a, STATIC,   SINGULAR, INT32,    code,              3)
#define SAckProto_CALLBACK pb_default_field_callback
#define SAckProto_DEFAULT NULL

extern const pb_msgdesc_t AckProto_msg;
extern const pb_msgdesc_t SAckProto_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AckProto_fields &AckProto_msg
#define SAckProto_fields &SAckProto_msg

/* Maximum encoded size of messages (where known) */
/* AckProto_size depends on runtime parameters */
/* SAckProto_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
