/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_UAV_CTL_PB_H_INCLUDED
#define PB_UAV_CTL_PB_H_INCLUDED
#include "../nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _InstructionProto {
    pb_callback_t droneId;
    uint32_t inst; /* 1-解锁 2-起飞 3-去作业 4-返航 5-降落 6-暂停 7-继续 8-开始推流 9-结束推流 */
} InstructionProto;

typedef struct _WaypointProto {
    uint32_t index;
    double lat;
    double lng;
    int32_t alt; /* cm */
    int32_t height; /* cm */
    uint32_t wlMission;
    int32_t wlParam;
    uint32_t wpMission;
    int32_t wpParam;
} WaypointProto;

typedef struct _WaypointGroupProto {
    pb_callback_t droneId;
    pb_callback_t routeId;
    pb_callback_t wps;
} WaypointGroupProto;

typedef struct _RouteProto {
    pb_callback_t droneId;
    pb_callback_t routeId;
    uint32_t wpNum;
    int32_t height; /* cm */
    int32_t speed; /* cm/s */
    int32_t spray; /* ml/mu */
    int32_t width; /* cm */
} RouteProto;

typedef struct _GimbalPos {
    uint32_t type; /* 0-停止 1-吊舱向上 2-吊舱向下 3-吊舱向左 4-吊舱向右 */
    uint32_t strength; /* 速度 0-100% */
} GimbalPos;

typedef struct _GimbalZoom {
    uint32_t type; /* 0-停止变焦 1-拉远 2-拉近 */
    uint32_t strength; /* 速度 0-100% */
} GimbalZoom;

typedef struct _GimbalPoint {
    /* 图像坐上角为原点 */
    uint32_t x; /* 水平坐标(百分比0-100) */
    uint32_t y; /* 垂直坐标(百分比0-100) */
} GimbalPoint;

typedef struct _GimbalTargetTrack {
    /* 图像坐上角为原点 */
    uint32_t left; /* 左上顶点 水平位置 x(百分比0-100) */
    uint32_t top; /* 左上顶点 垂直位置 y(百分比0-100) */
    uint32_t right; /* 右下顶点 水平位置 x(百分比0-100) */
    uint32_t bottom; /* 右下顶点 垂直位置 y(百分比0-100) */
} GimbalTargetTrack;

typedef struct _GimbalProto {
    pb_callback_t droneId;
    uint32_t inst; /* cmdId 1-方向 2-拍照 3-开始录像 4-结束录像 5-变焦 6-指点移动(将吊舱位置移动到x,y位置) 7-一键回中 8-开始目标跟踪 9-停止目标跟踪 */
    pb_size_t which_payload;
    union {
        GimbalPos pos; /* cmd=1-方向 */
        GimbalZoom zoom; /* cmd=5-变焦 */
        GimbalPoint point; /* cmd=6-指点移动 */
        GimbalTargetTrack track; /* cmd=8-目标跟踪 */
    } payload;
} GimbalProto;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define InstructionProto_init_default            {{{NULL}, NULL}, 0}
#define WaypointProto_init_default               {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define WaypointGroupProto_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define RouteProto_init_default                  {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0}
#define GimbalProto_init_default                 {{{NULL}, NULL}, 0, 0, {GimbalPos_init_default}}
#define GimbalPos_init_default                   {0, 0}
#define GimbalZoom_init_default                  {0, 0}
#define GimbalPoint_init_default                 {0, 0}
#define GimbalTargetTrack_init_default           {0, 0, 0, 0}
#define InstructionProto_init_zero               {{{NULL}, NULL}, 0}
#define WaypointProto_init_zero                  {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define WaypointGroupProto_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define RouteProto_init_zero                     {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0}
#define GimbalProto_init_zero                    {{{NULL}, NULL}, 0, 0, {GimbalPos_init_zero}}
#define GimbalPos_init_zero                      {0, 0}
#define GimbalZoom_init_zero                     {0, 0}
#define GimbalPoint_init_zero                    {0, 0}
#define GimbalTargetTrack_init_zero              {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define InstructionProto_droneId_tag             1
#define InstructionProto_inst_tag                2
#define WaypointProto_index_tag                  1
#define WaypointProto_lat_tag                    2
#define WaypointProto_lng_tag                    3
#define WaypointProto_alt_tag                    4
#define WaypointProto_height_tag                 5
#define WaypointProto_wlMission_tag              6
#define WaypointProto_wlParam_tag                7
#define WaypointProto_wpMission_tag              8
#define WaypointProto_wpParam_tag                9
#define WaypointGroupProto_droneId_tag           1
#define WaypointGroupProto_routeId_tag           2
#define WaypointGroupProto_wps_tag               3
#define RouteProto_droneId_tag                   1
#define RouteProto_routeId_tag                   2
#define RouteProto_wpNum_tag                     3
#define RouteProto_height_tag                    4
#define RouteProto_speed_tag                     5
#define RouteProto_spray_tag                     6
#define RouteProto_width_tag                     7
#define GimbalPos_type_tag                       1
#define GimbalPos_strength_tag                   2
#define GimbalZoom_type_tag                      1
#define GimbalZoom_strength_tag                  2
#define GimbalPoint_x_tag                        1
#define GimbalPoint_y_tag                        2
#define GimbalTargetTrack_left_tag               1
#define GimbalTargetTrack_top_tag                2
#define GimbalTargetTrack_right_tag              3
#define GimbalTargetTrack_bottom_tag             4
#define GimbalProto_droneId_tag                  1
#define GimbalProto_inst_tag                     2
#define GimbalProto_pos_tag                      3
#define GimbalProto_zoom_tag                     4
#define GimbalProto_point_tag                    5
#define GimbalProto_track_tag                    6

/* Struct field encoding specification for nanopb */
#define InstructionProto_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   droneId,           1) \
X(a, STATIC,   SINGULAR, UINT32,   inst,              2)
#define InstructionProto_CALLBACK pb_default_field_callback
#define InstructionProto_DEFAULT NULL

#define WaypointProto_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, DOUBLE,   lat,               2) \
X(a, STATIC,   SINGULAR, DOUBLE,   lng,               3) \
X(a, STATIC,   SINGULAR, INT32,    alt,               4) \
X(a, STATIC,   SINGULAR, INT32,    height,            5) \
X(a, STATIC,   SINGULAR, UINT32,   wlMission,         6) \
X(a, STATIC,   SINGULAR, INT32,    wlParam,           7) \
X(a, STATIC,   SINGULAR, UINT32,   wpMission,         8) \
X(a, STATIC,   SINGULAR, INT32,    wpParam,           9)
#define WaypointProto_CALLBACK NULL
#define WaypointProto_DEFAULT NULL

#define WaypointGroupProto_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   droneId,           1) \
X(a, CALLBACK, SINGULAR, STRING,   routeId,           2) \
X(a, CALLBACK, REPEATED, MESSAGE,  wps,               3)
#define WaypointGroupProto_CALLBACK pb_default_field_callback
#define WaypointGroupProto_DEFAULT NULL
#define WaypointGroupProto_wps_MSGTYPE WaypointProto

#define RouteProto_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   droneId,           1) \
X(a, CALLBACK, SINGULAR, STRING,   routeId,           2) \
X(a, STATIC,   SINGULAR, UINT32,   wpNum,             3) \
X(a, STATIC,   SINGULAR, INT32,    height,            4) \
X(a, STATIC,   SINGULAR, INT32,    speed,             5) \
X(a, STATIC,   SINGULAR, INT32,    spray,             6) \
X(a, STATIC,   SINGULAR, INT32,    width,             7)
#define RouteProto_CALLBACK pb_default_field_callback
#define RouteProto_DEFAULT NULL

#define GimbalProto_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   droneId,           1) \
X(a, STATIC,   SINGULAR, UINT32,   inst,              2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pos,payload.pos),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,zoom,payload.zoom),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,point,payload.point),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,track,payload.track),   6)
#define GimbalProto_CALLBACK pb_default_field_callback
#define GimbalProto_DEFAULT NULL
#define GimbalProto_payload_pos_MSGTYPE GimbalPos
#define GimbalProto_payload_zoom_MSGTYPE GimbalZoom
#define GimbalProto_payload_point_MSGTYPE GimbalPoint
#define GimbalProto_payload_track_MSGTYPE GimbalTargetTrack

#define GimbalPos_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   strength,          2)
#define GimbalPos_CALLBACK NULL
#define GimbalPos_DEFAULT NULL

#define GimbalZoom_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   strength,          2)
#define GimbalZoom_CALLBACK NULL
#define GimbalZoom_DEFAULT NULL

#define GimbalPoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 2)
#define GimbalPoint_CALLBACK NULL
#define GimbalPoint_DEFAULT NULL

#define GimbalTargetTrack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   left,              1) \
X(a, STATIC,   SINGULAR, UINT32,   top,               2) \
X(a, STATIC,   SINGULAR, UINT32,   right,             3) \
X(a, STATIC,   SINGULAR, UINT32,   bottom,            4)
#define GimbalTargetTrack_CALLBACK NULL
#define GimbalTargetTrack_DEFAULT NULL

extern const pb_msgdesc_t InstructionProto_msg;
extern const pb_msgdesc_t WaypointProto_msg;
extern const pb_msgdesc_t WaypointGroupProto_msg;
extern const pb_msgdesc_t RouteProto_msg;
extern const pb_msgdesc_t GimbalProto_msg;
extern const pb_msgdesc_t GimbalPos_msg;
extern const pb_msgdesc_t GimbalZoom_msg;
extern const pb_msgdesc_t GimbalPoint_msg;
extern const pb_msgdesc_t GimbalTargetTrack_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define InstructionProto_fields &InstructionProto_msg
#define WaypointProto_fields &WaypointProto_msg
#define WaypointGroupProto_fields &WaypointGroupProto_msg
#define RouteProto_fields &RouteProto_msg
#define GimbalProto_fields &GimbalProto_msg
#define GimbalPos_fields &GimbalPos_msg
#define GimbalZoom_fields &GimbalZoom_msg
#define GimbalPoint_fields &GimbalPoint_msg
#define GimbalTargetTrack_fields &GimbalTargetTrack_msg

/* Maximum encoded size of messages (where known) */
/* InstructionProto_size depends on runtime parameters */
/* WaypointGroupProto_size depends on runtime parameters */
/* RouteProto_size depends on runtime parameters */
/* GimbalProto_size depends on runtime parameters */
#define GimbalPoint_size                         12
#define GimbalPos_size                           12
#define GimbalTargetTrack_size                   24
#define GimbalZoom_size                          12
#define UAV_CTL_PB_H_MAX_SIZE                    WaypointProto_size
#define WaypointProto_size                       80

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
