/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_UAV_PB_H_INCLUDED
#define PB_UAV_PB_H_INCLUDED
#include "../nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _TrackProto {
    uint64_t timestamp;
    pb_callback_t droneId;
    double lat;
    double lng;
    int32_t alt; /* cm */
    int32_t height; /* cm */
    int32_t hvel; /* cm/s */
    int32_t vvel; /* cm/s */
    uint32_t satellite;
    uint32_t locType;
    int32_t yaw; /* 0.1 degree */
    int32_t pitch; /* 0.1 degree */
    int32_t roll; /* 0.1 degree */
    bool onAir;
    uint32_t ftime;
    float area;
    uint32_t flow; /* ml/min */
    uint32_t dose; /* ml */
    uint32_t warning;
    uint32_t pump;
} TrackProto;

typedef struct _BatteryProto {
    uint64_t timestamp;
    pb_callback_t battId;
    uint32_t cycle;
    uint32_t status;
    uint32_t percent;
    uint32_t voltage; /* mV */
    int32_t current; /* mA */
    int32_t temperature; /* 0.1 degree */
    pb_callback_t cells;
} BatteryProto;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TrackProto_init_default                  {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BatteryProto_init_default                {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}}
#define TrackProto_init_zero                     {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BatteryProto_init_zero                   {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define TrackProto_timestamp_tag                 1
#define TrackProto_droneId_tag                   2
#define TrackProto_lat_tag                       3
#define TrackProto_lng_tag                       4
#define TrackProto_alt_tag                       5
#define TrackProto_height_tag                    6
#define TrackProto_hvel_tag                      7
#define TrackProto_vvel_tag                      8
#define TrackProto_satellite_tag                 9
#define TrackProto_locType_tag                   10
#define TrackProto_yaw_tag                       51
#define TrackProto_pitch_tag                     52
#define TrackProto_roll_tag                      53
#define TrackProto_onAir_tag                     54
#define TrackProto_ftime_tag                     101
#define TrackProto_area_tag                      102
#define TrackProto_flow_tag                      103
#define TrackProto_dose_tag                      104
#define TrackProto_warning_tag                   105
#define TrackProto_pump_tag                      106
#define BatteryProto_timestamp_tag               1
#define BatteryProto_battId_tag                  2
#define BatteryProto_cycle_tag                   3
#define BatteryProto_status_tag                  4
#define BatteryProto_percent_tag                 5
#define BatteryProto_voltage_tag                 6
#define BatteryProto_current_tag                 7
#define BatteryProto_temperature_tag             8
#define BatteryProto_cells_tag                   10

/* Struct field encoding specification for nanopb */
#define TrackProto_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, CALLBACK, SINGULAR, STRING,   droneId,           2) \
X(a, STATIC,   SINGULAR, DOUBLE,   lat,               3) \
X(a, STATIC,   SINGULAR, DOUBLE,   lng,               4) \
X(a, STATIC,   SINGULAR, INT32,    alt,               5) \
X(a, STATIC,   SINGULAR, INT32,    height,            6) \
X(a, STATIC,   SINGULAR, INT32,    hvel,              7) \
X(a, STATIC,   SINGULAR, INT32,    vvel,              8) \
X(a, STATIC,   SINGULAR, UINT32,   satellite,         9) \
X(a, STATIC,   SINGULAR, UINT32,   locType,          10) \
X(a, STATIC,   SINGULAR, INT32,    yaw,              51) \
X(a, STATIC,   SINGULAR, INT32,    pitch,            52) \
X(a, STATIC,   SINGULAR, INT32,    roll,             53) \
X(a, STATIC,   SINGULAR, BOOL,     onAir,            54) \
X(a, STATIC,   SINGULAR, UINT32,   ftime,           101) \
X(a, STATIC,   SINGULAR, FLOAT,    area,            102) \
X(a, STATIC,   SINGULAR, UINT32,   flow,            103) \
X(a, STATIC,   SINGULAR, UINT32,   dose,            104) \
X(a, STATIC,   SINGULAR, UINT32,   warning,         105) \
X(a, STATIC,   SINGULAR, UINT32,   pump,            106)
#define TrackProto_CALLBACK pb_default_field_callback
#define TrackProto_DEFAULT NULL

#define BatteryProto_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, CALLBACK, SINGULAR, STRING,   battId,            2) \
X(a, STATIC,   SINGULAR, UINT32,   cycle,             3) \
X(a, STATIC,   SINGULAR, UINT32,   status,            4) \
X(a, STATIC,   SINGULAR, UINT32,   percent,           5) \
X(a, STATIC,   SINGULAR, UINT32,   voltage,           6) \
X(a, STATIC,   SINGULAR, INT32,    current,           7) \
X(a, STATIC,   SINGULAR, INT32,    temperature,       8) \
X(a, CALLBACK, REPEATED, UINT32,   cells,            10)
#define BatteryProto_CALLBACK pb_default_field_callback
#define BatteryProto_DEFAULT NULL

extern const pb_msgdesc_t TrackProto_msg;
extern const pb_msgdesc_t BatteryProto_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TrackProto_fields &TrackProto_msg
#define BatteryProto_fields &BatteryProto_msg

/* Maximum encoded size of messages (where known) */
/* TrackProto_size depends on runtime parameters */
/* BatteryProto_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
